#!/bin/sh
feh --bg-center $DOTFILES/resources/bg.* &
picom -C &
sxhkd &
dunst &
polybar -r top &
polybar -r bottom &
udiskie &
xss-lock -l -- lock &
xsetroot -cursor_name left_ptr &
pidof bspswallow || bspswallow Zathura vlc feh &

bspc monitor eDP1 -d I II III IV V VI
bspc monitor DP2 -d DP2

bspc config border_width 1
bspc config window_gap 12

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config click_to_focus none
bspc config focus_follows_pointer true

bspc config automatic_scheme "alternate"

bspc config normal_border_color "#333333"
bspc config active_border_color "#333333"
bspc config focused_border_color "#aaaaaa"
bspc config presel_feedback_color "#aaaaaa"


bspc desktop VI -l monocle
bspc rule -a Firefox desktop=VI follow=off focus=off locked=on
bspc rule -a Zathura state=tiled
