#!/bin/sh
feh --bg-center $DOTFILES/resources/bg.* &
picom -C &
sxhkd &
dunst &
polybar top &
polybar bottom &
udiskie &
xss-lock -l -- lock &
xsetroot -cursor_name left_ptr &
pgrep bspswallow || bspswallow Zathura vlc feh &

autorandr -c
bspc monitor eDP1 -d I II III IV V VI

bspc config border_width 1
bspc config window_gap 12

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config click_to_focus none
bspc config focus_follows_pointer true

bspc config automatic_scheme "alternate"

bspc config normal_border_color "#333333"
bspc config active_border_color "#333333"
bspc config focused_border_color "#aaaaaa"
bspc config presel_feedback_color "#aaaaaa"

bspc rule -a Firefox follow=off focus=off locked=on
bspc rule -a Zathura state=tiled

bspc config external_rules_command "$DOTFILES/resources/bspwm_external_rules.sh"
