set number
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set laststatus=0
set relativenumber
syntax on

map <silent> <F7>   :tabp<CR>
map <silent> <F8>   :tabn<CR>
map <silent> <F2>   :NERDTreeToggle<CR>
map          <F3>   :let @+=@"<CR>
map <silent> <F10>  :ALEToggle<CR>
map <silent> <F11>  :ALEFix<CR>

set listchars=tab:>-,trail:.
set list

set t_Co=256

hi CursorLine term=bold cterm=bold ctermbg=black

set hidden

au BufRead /tmp/mutt-* set tw=72

:highlight ALEError ctermbg=none cterm=underline
:highlight ALEWarning ctermbg=none cterm=underline
let g:ale_enabled = 0
let g:ale_lint_on_enter = 0
let g:ale_lint_on_text_changed = 'never'
let g:ale_linters_explicit = 1
let g:ale_linters = {
  \ 'c': ['clang'],
  \ 'cpp': ['clang'],
  \ 'rust': ['rls'],
  \ }
let g:ale_fixers = {
  \ '*': ['remove_trailing_lines', 'trim_whitespace'],
  \ 'c': ['clang-format'],
  \ 'cpp': ['clang-format'],
  \ }

call plug#begin('~/.local/share/nvim/plugged')
Plug 'scrooloose/nerdtree'
Plug 'w0rp/ale'
Plug 'tomtom/tcomment_vim'
Plug 'ervandew/supertab'
call plug#end()
