#!/bin/bash

export AWT_TOOLKIT=MToolkit
wmname compiz
xrandr --output eDP1 --auto --primary

SESSION=${2:-bspwm}

case $SESSION in
    bspwm) exec bspwm;;
    kde) exec startplasma-x11;;
    *) exec $2;;
esac
