#!/bin/bash

export AWT_TOOLKIT=MToolkit
export XDG_SESSION_TYPE=x11
export GDK_BACKEND=x11
wmname compiz
xmodmap $HOME/.xmodmaprc

SESSION=${2:-bspwm}

case $SESSION in
    bspwm) exec bspwm;;
    gnome) exec gnome-session;;
    *) exec $2;;
esac
