#!/bin/sh

export _JAVA_AWT_WM_NONREPARENTING=1
xrandr --output eDP1 --auto --primary

SESSION=${2:-bspwm}

case $SESSION in
    bspwm) exec bspwm;;
    kde) exec startplasma-x11;;
    *) exec $2;;
esac
